#!/usr/bin/env python

Import("env")
Import("env_tg")

env_renderer = env_tg.Clone()
renderer_sources = Glob("*.cpp")
if env["platform"] == "osx":
    # macOS binds an IOSurface and never has to measure a Vulkan allocation.
    renderer_sources = [f for f in renderer_sources if f.name != "vulkan_memory_probe.cpp"]
env_renderer.add_source_files(env.modules_sources, renderer_sources)
