#!/usr/bin/env python

Import("env")
Import("env_modules")

env_slug = env_modules.Clone()

if env["builtin_freetype"]:
    env_slug.Prepend(CPPPATH=["#thirdparty/freetype/include"])

env_slug.add_source_files(env.modules_sources, "*.cpp")
